kind: pipeline
name: default
type: docker

globals:
  - &docker_commons
    image: plugins/docker
    settings:
      username: drone
      password:
        from_secret: registry_password
      auto_tag: true
      registry: registry.florianbeetz.de
      use_cache: true
    volumes:
      - name: docker
        path: /var/lib/docker

steps:
  - name: prepare
    image: busybox
    commands:
      - mkdir -p /cache/${DRONE_REPO}/docker
    volumes:
      - name: cache
        path: /cache

  - name: "inventory: build image"
    <<: *docker_commons
    settings:
      repo: registry.florianbeetz.de/ma-rest/inventory
      context: inventory-service
      dockerfile: inventory-service/Dockerfile

  - name: "order: build image"
    <<: *docker_commons
    settings:
      repo: registry.florianbeetz.de/ma-rest/order
      context: order-service
      dockerfile: order-service/Dockerfile

  - name: "payment: build image"
    <<: *docker_commons
    settings:
      repo: registry.florianbeetz.de/ma-rest/payment
      context: payment-service
      dockerfile: payment-service/Dockerfile


  - name: "shipping: build image"
    <<: *docker_commons
    settings:
      repo: registry.florianbeetz.de/ma-rest/shipping
      context: shipping-service
      dockerfile: shipping-service/Dockerfile

volumes:
  - name: cache
    host:
      path: /var/cache
  - name: docker
    host:
      path: /var/cache/${DRONE_REPO}/docker