version: '3'

services:
  traefik:
    image: traefik
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "8080:80"
      - "8090:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"


  inventory:
    build: ./inventory-service
    environment:
      - INVENTORY_DB_HOST=inventory_db
      - INVENTORY_DB_PORT=5432
      - INVENTORY_DB_DATABASE=postgres
      - INVENTORY_DB_USER=postgres
      - INVENTORY_DB_PASSWORD=${INVENTORY_DB_PASSWORD}
    depends_on:
      - inventory_db
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.inventory.rule=PathPrefix(`/inventory/`)"
      - "traefik.http.routers.inventory.entrypoints=web"


  inventory_db:
    image: postgres
    ports:
    - 5434:5432
    environment:
      - POSTGRES_PASSWORD=${INVENTORY_DB_PASSWORD}

  orders:
    build: ./order-service
    environment:
      - ORDER_DB_HOST=order_db
      - ORDER_DB_PORT=5432
      - ORDER_DB_DATABASE=postgres
      - ORDER_DB_USER=postgres
      - ORDER_DB_PASSWORD=${ORDER_DB_PASSWORD}
    depends_on:
      - order_db
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.order.rule=PathPrefix(`/order/`)"
      - "traefik.http.routers.order.entrypoints=web"

  order_db:
    image: postgres
    ports:
    - 5432:5432
    environment:
      - POSTGRES_PASSWORD=${ORDER_DB_PASSWORD}

  shipping:
    build:
      ./shipping-service
    environment:
      - SHIPPING_DB_HOST=shipping_db
      - SHIPPING_DB_PORT=5432
      - SHIPPING_DB_DATABASE=postgres
      - SHIPPING_DB_USER=postgres
      - SHIPPING_DB_PASSWORD=${SHIPPING_DB_PASSWORD}
    depends_on:
      - shipping_db
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.shipping.rule=PathPrefix(`/shipping/`)"
      - "traefik.http.routers.shipping.entrypoints=web"

  shipping_db:
    image: postgres
    ports:
      - 5433:5432
    environment:
      - POSTGRES_PASSWORD=${SHIPPING_DB_PASSWORD}

  payment:
    build:
      ./payment-service
    environment:
      - PAYMENT_DB_HOST=payment_db
      - PAYMENT_DB_PORT=5432
      - PAYMENT_DB_DATABASE=postgres
      - PAYMENT_DB_USER=postgres
      - PAYMENT_DB_PASSWORD=${PAYMENT_DB_PASSWORD}
    depends_on:
      - payment_db
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.payment.rule=PathPrefix(`/payment/`)"
      - "traefik.http.routers.payment.entrypoints=web"

  payment_db:
    image: postgres
    ports:
      - 5435:5432
    environment:
      - POSTGRES_PASSWORD=${PAYMENT_DB_PASSWORD}