logging:
  level:
    .: INFO
    de.florianbeetz: DEBUG
    org.springframework.web.servlet.DispatcherServlet: DEBUG

server:
  servlet:
    context-path: /shipping

spring:
  datasource:
    url: jdbc:postgresql://${SHIPPING_DB_HOST}:${SHIPPING_DB_PORT}/${SHIPPING_DB_DATABASE}
    username: ${SHIPPING_DB_USER}
    password: ${SHIPPING_DB_PASSWORD}
  jpa:
    generate-ddl: true

springdoc:
  api-docs:
    path: /api/docs