application:
  title: Shipping API
  version: 1
  description: Manages shipments of orders

  housekeeping:
    order-update: "0 * * * * *" # every minute

logging:
  level:
    .: INFO
    de.florianbeetz: DEBUG
    org.springframework.web.servlet.DispatcherServlet: DEBUG
    org.springframework.security: DEBUG

server:
  servlet:
    context-path: /shipping

keycloak:
  realm: ma-rest-shop
  auth-server-url: ${SHIPPING_AUTH_URL:http://localhost/auth} # default value required for testing
  ssl-required: none
  resource: ${SHIPPING_AUTH_CLIENT}
  credentials:
    secret: ${SHIPPING_AUTH_SECRET}
  use-resource-role-mappings: true
  bearer-only: true

spring:
  datasource:
    url: jdbc:postgresql://${SHIPPING_DB_HOST}:${SHIPPING_DB_PORT}/${SHIPPING_DB_DATABASE}
    username: ${SHIPPING_DB_USER}
    password: ${SHIPPING_DB_PASSWORD}
  jpa:
    generate-ddl: true

springdoc:
  api-docs:
    path: /api/docs