application:
  title: Order API
  version: 1
  description: Accepts and manages orders

  api:
    shipping:
      base-url: http://host.docker.internal:8080/shipping/api/v1
    payment:
      base-url: http://host.docker.internal:8080/payment/api/v1

logging:
  level:
    .: INFO
    de.florianbeetz: DEBUG
    org.springframework.web.servlet.DispatcherServlet: DEBUG

server:
  servlet:
    context-path: /order

spring:
  datasource:
    url: jdbc:postgresql://${ORDER_DB_HOST}:${ORDER_DB_PORT}/${ORDER_DB_DATABASE}
    username: ${ORDER_DB_USER}
    password: ${ORDER_DB_PASSWORD}
  jpa:
    generate-ddl: true

springdoc:
  api-docs:
    path: /api/docs