application:
  title: Inventory API
  version: 1
  description: Manages inventory in warehouses

logging:
  level:
    .: INFO
    de.florianbeetz: DEBUG
    org.springframework.web.servlet.DispatcherServlet: DEBUG
    org.springframework.security: DEBUG

server:
  servlet:
    context-path: /inventory

keycloak:
  realm: ma-rest-shop
  auth-server-url: ${INVENTORY_AUTH_URL:http://localhost/auth} # default value required for testing
  ssl-required: none
  resource: ${INVENTORY_AUTH_CLIENT}
  credentials:
    secret: ${INVENTORY_AUTH_SECRET}
  use-resource-role-mappings: true
  bearer-only: true

spring:
  datasource:
    url: jdbc:postgresql://${INVENTORY_DB_HOST}:${INVENTORY_DB_PORT}/${INVENTORY_DB_DATABASE}
    username: ${INVENTORY_DB_USER}
    password: ${INVENTORY_DB_PASSWORD}
  jpa:
    generate-ddl: true

springdoc:
  api-docs:
    path: /api/docs