# curl -X POST 'http://host.docker.internal:8080/auth/realms/ma-rest-shop/protocol/openid-connect/token'
# --header 'Content-Type: application/x-www-form-urlencoded'
# --data-urlencode 'grant_type=password'
# --data-urlencode 'client_id=<CLIENT_ID>'
# --data-urlencode 'client_secret=<CLIENT_SECRET>'
# --data-urlencode 'username=<USERNAME>'
# --data-urlencode 'password=<PASSWORD>'
POST http://host.docker.internal:8080/auth/realms/ma-rest-shop/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

grant_type=password&client_id=external&client_secret=ac36f046-59b2-4073-acb9-36c91c6bff29&username=admin&password=admin

###

POST http://host.docker.internal:8080/auth/realms/ma-rest-shop/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded
Authorization: Basic b3JkZXI6YTkwZmIyOGUtZDczOC00MmYyLTgwMDctMzM1YjU1NTAyMmI1

grant_type=client_credentials


###

GET http://host.docker.internal:8080/inventory/api/v1/warehouse/
accept: application/hal+json
authorization: bearer {{token}}

###

# curl -X POST "http://host.docker.internal:8080/inventory/api/v1/warehouse/" -H "accept: application/hal+json" -H "Content-Type: application/json" -d "{\"name\":\"Warehouse 1\"}"
POST http://host.docker.internal:8080/inventory/api/v1/warehouse/
accept: application/hal+json
Content-Type: application/json
authorization: bearer {{token}}

{"name":"Warehouse 1"}

###

# curl -X POST "http://host.docker.internal:8080/inventory/api/v1/item/" -H "accept: application/hal+json" -H "Content-Type: application/json" -d "{\"title\":\"Item 1\",\"price\":3.5}"
POST http://host.docker.internal:8080/inventory/api/v1/item/
accept: application/hal+json
Content-Type: application/json
authorization: bearer {{token}}

{
  "title": "Döner",
  "price": 3.5
}

###

# curl -X POST "http://host.docker.internal:8080/inventory/api/v1/item/4/stock/" -H "accept: application/hal+json" -H "Content-Type: application/json" -d "{\"available\":20,\"inStock\":20,\"warehouse\":\"http://host.docker.internal:8080/inventory/api/v1/warehouse/1\"}"
POST http://host.docker.internal:8080/inventory/api/v1/item/5/stock/
accept: application/hal+json
Content-Type: application/json
authorization: bearer {{token}}

{
  "available": 20,
  "inStock": 20,
  "warehouse": "http://host.docker.internal:8080/inventory/api/v1/warehouse/4"
}

###

# curl -X POST "http://host.docker.internal:8080/order/api/v1/order/" -H "accept: */*" -H "Content-Type: application/json" -d "{\"items\":[{\"item\":\"http://host.docker.internal:8080/inventory/api/v1/item/2\",\"amount\":1}],\"status\":\"created\",\"address\":{\"street\":\"Luitpoldstr. 1\",\"city\":\"Bamberg\",\"zip\":\"96052\"}}"
POST http://host.docker.internal:8080/order/api/v1/order/
accept: */*
Content-Type: application/json

{
  "items": [
    {
      "item": "http://host.docker.internal:8080/inventory/api/v1/item/5",
      "amount": 1
    }
  ],
  "status": "created",
  "address": {
    "street": "Luitpoldstr. 1",
    "city": "Bamberg",
    "zip": "96052"
  }
}